### ISSUE TITLE
Add links to members list

### ISSUE THREAD

**Issue by PabRod** [Team-Nabla/.github#1]
## Problem

Ideally, the members list should contain a link to whatever website you want to link (eScience profile, GitHub, LinkedIn, personal website, ...). At the moment, this is missing.

## Solution

Please, send me your desired link. Conversely, you can also edit it yourself.

### Completion status

- [x] @apalha
- [x] @APJansen
- [x] @goord
- [x] @luisaforozco
- [x] @PabRod

**Comment by goord** [comment]
Hi Pablo can you use my escience center page?  https://www.esciencecenter.nl/team/dr-gijs-van-den-oord/
