### ISSUE TITLE
Write a title and abstract for the Section Meeting talks

### ISSUE THREAD

**Issue by PabRod** [Team-Nabla/.github#11]
Provide Nico with a description of our talks for the next section meeting. Please tick yourself as done after sending it:

- [x] Murilo
- [x] Aron
- [x] Luisa

**Comment by luisaforozco** [comment]
I suggest gathering the titles in this issue and then sending a **single** email to Nico.
Mine is:
**State of art of diffusion models for molecule generation**
Luisa will present some literature about recent advances in generative AI for chemistry, explain what diffusion models are and outlay different approaches found in the literature.

**Comment by APJansen** [comment]
Here's mine:

**Learning what protons are made of**
Aron will present the proton structure project, in which we use machine learning and data from high energy collisions to determine how much of each flavor of quark is inside a proton.

**Comment by Cmurilochem** [comment]
and finally, mine:

**Bridging Quantum Chemistry and Quantum Computing***
Carlos will present the current state of the QCforQC project, providing an overview of its objectives, key findings, and potential implications for the field of quantum chemistry, shedding light on the exciting possibilities at the intersection of quantum chemistry and near-term quantum computing

**Comment by PabRod** [comment]
Thank you, everyone! I'll forward this to Nico.
