### ISSUE TITLE
Add personal and project information [Carlos]

### ISSUE THREAD

**Issue by apalha** [Team-Nabla/.github#4]
Hi Carlos,

Welcome to the repo of the team.

The team's page is located here:  [https://github.com/Team-Nabla/](https://github.com/Team-Nabla/)

This page contains:
- List of members (with links to their webpages, may be either be your own website, your webpage at the eScience Center, your github page, or something similar)
- List of projects (with links to either the Research Software Directory, if still there is no page internally, or the internal page)

Whe you have time, could you:

1. Add yourself to the list of team members, this [file](https://github.com/Team-Nabla/.github/blob/main/profile/README.md)
2. Add your current project
     2.1 Add entry on the main page to link to the internal page of the project (preferrable) or to the RSD
     2.2 Create the internal page of the project. You can follow the same structure as the one of the DeepDip project, see [here](https://github.com/Team-Nabla/.github/tree/main/profile/pages/projects/deepdip)

**NOTE:** To do this, clone the repo ([https://github.com/Team-Nabla/.github](https://github.com/Team-Nabla/.github)), make a new branch, make the changes, commit and pull, and finally make a pull request.

Thanks a lot! If you have any questions just ask me.

**Comment by luisaforozco** [comment]
@Cmurilochem should this issue still be open?

**Comment by Cmurilochem** [comment]
> @Cmurilochem should this issue still be open?

Hi @luisaforozco. No. I've done all my updates already. I will close this issue. Thanks
